name: Build
on:
  push:
    branches:
      - master

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: sergioramos/yarn-actions/install@master
        with:
          frozen-lockfile: true
      - name: Setup
        run: yarn global add @angular/cli
      - name: TypeScript Version
        run: npm install typescript@">=3.4.0 <3.5.0"
      - name: Build
        run: npm run build --prod
