

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
    - name: Deploy to Firebase
    - uses: lowply/deploy-firebase@v0.0.2
